project_name: drone-nomad
builds:
  -
    id: "drone-nomad"
    binary: drone-nomad
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    tags:
      - netgo
    # Custom ldflags templates.
    ldflags:
      - -X "main.version={{ .Version }}"
      - -X "main.commit={{ .Commit }}"
      - -X "main.date={{ .Date }}"

archives:
  -
    format: binary

dockers:
  -
    id: drone-nomad
    image_templates:
    - "docker.io/loq9/{{ .ProjectName }}:{{ .Tag }}"
    - "docker.io/loq9/{{ .ProjectName }}:latest"
    - "ghcr.io/loq9/{{ .ProjectName }}:{{ .Tag }}"
    - "ghcr.io/loq9/{{ .ProjectName }}:latest"
    dockerfile: "docker/Dockerfile.minimal"