FROM plugins/base:multiarch

LABEL maintainer="Marco Santos <marco.santos@loq9.com>" \
  org.label-schema.name="Drone Nomad" \
  org.label-schema.vendor="LOQ9" \
  org.label-schema.schema-version="1.0"

ADD release/linux/arm64/drone-nomad /bin/
ENTRYPOINT ["/bin/drone-nomad"]